update pipeline

diff --git a/.github/workflows/quality-gate.yml b/.github/workflows/quality-gate.yml
--- a/.github/workflows/quality-gate.yml
+++ b/.github/workflows/quality-gate.yml
@@ -69,15 +69,12 @@ jobs:
         echo "issue_count=$ERROR_COUNT" >> "$GITHUB_OUTPUT"
         echo "file_count=$FILE_COUNT" >> "$GITHUB_OUTPUT"
 
-        if [ "$ERROR_COUNT" -gt 0 ]; then
-          echo "::error::$ERROR_COUNT lint issue(s) found in $FILE_COUNT file(s)"
-          exit 1
-        else
+        if [ "$ERROR_COUNT" -eq 0 ]; then
           echo "::notice::No lint issues found"
         fi
     - name: Comment golangci-lint result on PR
       if: github.event_name == 'pull_request'
-      uses: actions/github-script@v7
+      uses: actions/github-script@v9
       with:
         script: |
           const issueCount = process.env.ISSUE_COUNT;
@@ -139,6 +136,11 @@ jobs:
       env:
         ISSUE_COUNT: ${{ steps.evaluate.outputs.issue_count }}
         FILE_COUNT: ${{ steps.evaluate.outputs.file_count }}
+    - name: Fail on lint errors
+      if: steps.evaluate.outputs.issue_count > 0
+      run: |
+        echo "::error::${{ steps.evaluate.outputs.issue_count }} lint issue(s) found in ${{ steps.evaluate.outputs.file_count }} file(s)"
+        exit 1
 
   sonarqube:
     if: always()
@@ -170,5 +172,3 @@ jobs:
         pollingTimeoutSec: 600
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-    - name: Sonarqube quality gate result
-      run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
